### ISSUE TITLE
show hourly data

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/loop-sensor-trends#25] opened 2020-03-30 17:11 UTC
- ashley needs to qa/qc the hourly models
- ashley needs to figure out how to visualize this in a plot and map
- at node level? at region level? at corridor level?

**Comment by JonathanEhrlichMC** [comment] 2020-03-30 17:30
I showed the hourly plots to Nick and Amy this morning. They thought it was definitely worth showing. Not sure the best way to visualize.

**Comment by eroten** [comment] 2021-08-06 16:36
Now considered a duplicate of #187

**Closed by eroten** 2021-08-06 16:36 UTC
Labels: enhancement
