### ISSUE TITLE
map - filter data by r_node_n_type

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/loop-sensor-trends#14] opened 2020-03-27 19:31 UTC
Stations, Exits/Entrances should be separate layers on the leaflet, IMO

**Comment by JonathanEhrlichMC** [comment] 2020-03-27 20:19
#8

**Comment by eroten** [comment] 2020-03-27 21:51
Closing, duplicate of #8

**Closed by eroten** 2020-03-27 21:51 UTC
Labels: shiny
